import type { Dorm, Occupant, DormContract, NewHireEmployee, InventoryItem, LeaseContract, LoginUser } from "../types";

export const themeDefault = {
  accentColor: "#2563EB",
  brandColor: "#0F172A",
  darkMode: false,
  statuses: ["사용중", "만료예정", "해지", "공실", "접수", "진행중", "완료", "거주중", "퇴실", "신규입주", "천안이동"],
  colorMap: {
    사용중: "#DCFCE7",
    만료예정: "#FEF3C7",
    해지: "#FEE2E2",
    공실: "#E5E7EB",
    접수: "#DBEAFE",
    진행중: "#E0E7FF",
    완료: "#DCFCE7",
    거주중: "#DCFCE7",
    퇴실: "#F3F4F6",
    신규입주: "#E0F2FE",
    천안이동: "#FCE7F3",
  },
};

export const demoUsers: LoginUser[] = [
  {
    id: crypto.randomUUID(),
    username: "admin",
    password: "admin1234",
    role: "admin",
    displayName: "총관리자",
    isActive: true,
    siteAccess: "전체",
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    username: "viewer",
    password: "viewer1234",
    role: "viewer",
    displayName: "조회전용",
    isActive: true,
    siteAccess: "전체",
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    username: "defect1",
    password: "defect1234",
    role: "maintenance_reporter",
    displayName: "기숙사관리자",
    isActive: true,
    siteAccess: "평택",
    createdAt: new Date().toISOString(),
  },
];

export const demoDorms: Dorm[] = [
  {
    id: crypto.randomUUID(),
    site: "평택",
    gender: "남",
    buildingName: "소사벌리더스하임",
    address: "경기도 평택시 비전동 1011 소사벌리더스하임",
    dong: "109동",
    roomHo: "2002호",
    pyeong: "34평",
    capacity: 6,
    contractStart: "2025-05-16",
    contractEnd: "2027-05-16",
    contractAmount: "2000/120",
    leaseStatus: "사용중",
    공동현관: "A동 1층",
    세대현관: "2002호",
    prepaymentDeposit: 2000000,
    realEstateName: "평택부동산",
    balanceDate: "2025-05-30",
    notes: "남자 기숙사",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    site: "평택",
    gender: "여",
    buildingName: "백석아이파크",
    address: "경기도 평택시 비전동 백석아이파크",
    dong: "108동",
    roomHo: "2202호",
    pyeong: "34평",
    capacity: 6,
    contractStart: "2025-06-01",
    contractEnd: "2026-06-15",
    contractAmount: "1800/110",
    leaseStatus: "만료예정",
    공동현관: "B동 1층",
    세대현관: "2202호",
    prepaymentDeposit: 1800000,
    realEstateName: "신한부동산",
    balanceDate: "2025-06-20",
    notes: "여자 기숙사",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    site: "천안",
    gender: "남",
    buildingName: "천안센트럴파크",
    address: "충남 천안시 서북구 백석동 천안센트럴파크",
    dong: "101동",
    roomHo: "1501호",
    pyeong: "32평",
    capacity: 6,
    contractStart: "2025-04-01",
    contractEnd: "2027-04-01",
    contractAmount: "2200/130",
    leaseStatus: "사용중",
    공동현관: "C동 1층",
    세대현관: "1501호",
    prepaymentDeposit: 2200000,
    realEstateName: "천안중앙부동산",
    balanceDate: "2025-04-15",
    notes: "남자 기숙사",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoOccupants = (dorms: Dorm[]): Occupant[] => [
  {
    id: crypto.randomUUID(),
    dormId: dorms[0]?.id ?? "",
    site: dorms[0]?.site ?? "평택",
    employeeName: "김민수",
    gender: "남",
    department: "생산1팀",
    phone: "010-1234-5678",
    moveInDate: "2025-05-16",
    moveOutDueDate: "2027-05-16",
    status: "거주중",
    isNewHireAssignment: false,
    notes: "정상 거주",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    dormId: dorms[1]?.id ?? "",
    site: dorms[1]?.site ?? "평택",
    employeeName: "이서연",
    gender: "여",
    department: "품질팀",
    phone: "010-9876-5432",
    moveInDate: "2025-06-10",
    moveOutDueDate: "2026-06-15",
    status: "만료예정",
    isNewHireAssignment: false,
    notes: "계약 만료 근접",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    dormId: dorms[2]?.id ?? "",
    site: dorms[2]?.site ?? "천안",
    employeeName: "박준호",
    gender: "남",
    department: "설비팀",
    phone: "010-5555-2222",
    moveInDate: "2025-04-05",
    moveOutDueDate: "2027-04-01",
    status: "신규입주",
    isNewHireAssignment: true,
    notes: "신입사원 배정",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoDormContracts: DormContract[] = [
  {
    id: crypto.randomUUID(),
    site: "평택",
    address: "경기도 평택시 비전동 1011",
    buildingName: "소사벌리더스하임",
    dong: "109동",
    roomHo: "2002호",
    pyeong: "24",
    landlordName: "김철수",
    landlordPhone: "010-1234-5678",
    realEstateName: "평택부동산",
    realEstatePhone: "031-123-4567",
    managementOfficePhone: "031-123-0000",
    공동현관: "A동 1층",
    세대현관: "2002호",
    contractStart: "",
    contractEnd: "",
    contractStatus: "진행중",
    contractAmount: "20,000,000",
    prepaymentDeposit: "2,000,000",
    deposit: "1,000,000",
    monthlyRentOrMaintenance: "120,000",
    contractType: "신규",
    gender: "남",
    notes: "계약 완료",
    registeredBy: "총관리자",
    modifiedBy: "총관리자",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoNewHires: NewHireEmployee[] = [
  {
    id: crypto.randomUUID(),
    site: "평택",
    gender: "남",
    name: "정승우",
    phone: "010-1111-2222",
    department: "개발팀",
    dormId: demoDorms[0]?.id ?? "",
    address: "경기도 평택시 비전동 1011 소사벌리더스하임",
    buildingName: "소사벌리더스하임",
    dong: "109동",
    roomHo: "2002호",
    공동현관: "A동 1층",
    세대현관: "2002호",
    expectedMoveInDate: "",
    moveInDate: "",
    expectedMoveOutDate: "",
    moveOutDate: "",
    actualMoveOutDate: "",
    cheonanMoveDate: "",
    residenceStatus: "거주중",
    moveInType: "신규",
    extensionReason: "",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoInventory: InventoryItem[] = [
  {
    id: crypto.randomUUID(),
    dormId: demoDorms[0]?.id ?? "",
    site: "평택",
    dormAddress: "경기도 평택시 세교동 123-45",
    buildingName: "세교빌딩",
    dong: "101",
    roomHo: "101",
    managerName: "김철수",
    managerPhone: "",
    itemName: "세탁기",
    quantity: 2,
    modelName: "WA21M8700GV",
    maker: "삼성전자",
    status: "정상",
    installationLocation: "1층 세탁실",
    purchaseDate: "2025-01-01",
    purchaseAmount: 1200000,
    issuedDate: "2025-01-15",
    proofFile: "",
    soldDate: "",
    soldAmount: 0,
    disposalDate: "",
    disposalReason: "",
    notes: "기숙사 1층 세탁실 설치",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    dormId: demoDorms[1]?.id ?? "",
    site: "평택",
    dormAddress: "경기도 평택시 세교동 456-78",
    buildingName: "세교빌딩",
    dong: "102",
    roomHo: "102",
    managerName: "이영희",
    managerPhone: "",
    itemName: "냉장고",
    quantity: 1,
    modelName: "RT35K5532S8",
    maker: "삼성전자",
    status: "정상",
    installationLocation: "2층 공용 주방",
    purchaseDate: "2025-02-01",
    purchaseAmount: 800000,
    issuedDate: "2025-02-10",
    proofFile: "",
    soldDate: "",
    soldAmount: 0,
    disposalDate: "",
    disposalReason: "",
    notes: "기숙사 2층 공용 주방 설치",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    dormId: demoDorms[2]?.id ?? "",
    site: "천안",
    dormAddress: "충청남도 천안시 동남구 789-01",
    buildingName: "천안빌딩",
    dong: "201",
    roomHo: "201",
    managerName: "박민수",
    managerPhone: "",
    itemName: "에어컨",
    quantity: 3,
    modelName: "AF17T7974WZN",
    maker: "삼성전자",
    status: "정상",
    installationLocation: "각 호실별",
    purchaseDate: "2025-03-01",
    purchaseAmount: 1800000,
    issuedDate: "2025-03-20",
    proofFile: "",
    soldDate: "",
    soldAmount: 0,
    disposalDate: "",
    disposalReason: "",
    notes: "각 호실별 설치",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const demoLeases: LeaseContract[] = [
  {
    id: crypto.randomUUID(),
    dateKey: "2025-01-15",
    addressName: "평택 세교동 아파트",
    dong: "101",
    ho: "101",
    pyeong: "24.5",
    contractAmount: "25000000",
    contractPeriod: "24개월",
    contractDate: "2025-01-15",
    prepaymentDeposit: 5000000,
    realEstateName: "평택부동산",
    balanceDate: "2025-02-15",
    site: "평택",
    gender: "남",
    notes: "신규 임대차 계약",
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    dateKey: "2025-02-20",
    addressName: "천안 동남구 빌라",
    dong: "202",
    ho: "202",
    pyeong: "19.8",
    contractAmount: "20000000",
    contractPeriod: "24개월",
    contractDate: "2025-02-20",
    prepaymentDeposit: 4000000,
    realEstateName: "천안부동산",
    balanceDate: "2025-03-20",
    site: "천안",
    gender: "여",
    notes: "재계약",
    updatedAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    dateKey: "2025-03-10",
    addressName: "평택 세교동 오피스텔",
    dong: "303",
    ho: "303",
    pyeong: "22.1",
    contractAmount: "22000000",
    contractPeriod: "24개월",
    contractDate: "2025-03-10",
    prepaymentDeposit: 4400000,
    realEstateName: "평택부동산",
    balanceDate: "2025-04-10",
    site: "평택",
    gender: "남",
    notes: "임대차 갱신",
    updatedAt: new Date().toISOString(),
  },
];
