-- Operational module tables for Supabase

CREATE TABLE IF NOT EXISTS cleaning_reports (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  report_date text,
  site text,
  dorm_id text,
  building_name text,
  address text,
  dong text,
  room_ho text,
  shared_entry text,
  unit_entry text,
  manager_user_id text,
  manager_name text,
  cleaner_name text,
  week_label text,
  month_label text,
  clean_status text,
  check_result text,
  score integer,
  memo text,
  before_photo_data_urls jsonb,
  after_photo_data_urls jsonb,
  reporter_user_id text,
  reporter_name text,
  confirmed_by text,
  confirmed_at text,
  created_by text,
  updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  is_deleted boolean DEFAULT FALSE,
  deleted_at timestamptz,
  deleted_by text
);

CREATE TABLE IF NOT EXISTS defect_requests (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  receipt_date text,
  site text,
  dorm_id text,
  inspector_name text,
  dorm_manager_name text,
  manager_user_id text,
  building_name text,
  dong text,
  ho text,
  shared_entry text,
  unit_entry text,
  road_address text,
  detail_address text,
  defect_status text,
  request_text text,
  complete_text text,
  reporter_user_id text,
  reporter_name text,
  request_photo_data_urls jsonb,
  completion_photo_data_urls jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  completed_at text,
  is_deleted boolean DEFAULT FALSE,
  deleted_at timestamptz,
  deleted_by text
);

CREATE TABLE IF NOT EXISTS inventory_items (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  dorm_id text,
  site text,
  dorm_address text,
  building_name text,
  dong text,
  room_ho text,
  manager_name text,
  item_name text,
  quantity integer,
  model_name text,
  maker text,
  status text,
  installation_location text,
  purchase_date text,
  purchase_amount numeric,
  issued_date text,
  proof_file text,
  sold_date text,
  sold_amount numeric,
  disposal_date text,
  disposal_reason text,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  is_deleted boolean DEFAULT FALSE,
  deleted_at timestamptz,
  deleted_by text
);

CREATE TABLE IF NOT EXISTS settlement_records (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  settlement_year text,
  settlement_month text,
  dorm_id text,
  misc_cost numeric,
  notes text,
  created_by text,
  updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settlement_items (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  settlement_year text,
  settlement_month text,
  dorm_id text,
  category text,
  details text,
  amount numeric,
  burden_type text,
  target_name text,
  memo text,
  created_by text,
  updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  target_type text,
  target_id text,
  action_type text,
  changed_by text,
  changed_at text,
  before_value text,
  after_value text,
  memo text,
  changes jsonb,
  created_by text,
  updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
